name: Service registry API
on:
  workflow_call:
    inputs:
      data:
        description: 'Data to save'
        required: true
        type: string
      action-path:
        description: 'Path to action in github'
        required: true
        type: string

env:
  VAULT_ADDR:            "https://vault.azure-omnicloud.com"
  ACTION_PATH:           ${{ github.event.inputs.action-path }}
  DATA_FROM_INPUT:       ${{ github.event.inputs.data }}
  PATH_TO_MONGO_SECRET:  "infrastructure/data/aws/mongo/mongo-primary"

jobs:
  write-to-mongo-regestry:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      #- uses: actions/checkout@v3

      # Decode input data
      - name: Decode input data
        run: |
          echo "DATA_FROM_INPUT"
          echo "ACTION_PATH"
          echo "DATA_TO_SAVE=$(echo $DATA_FROM_INPUT | base64 -d)" >> $GITHUB_ENV
          echo "PATH_TO_SAVE=$(echo $ACTION_PATH | base64 -d)" >> $GITHUB_ENV

      - name: Store service data in mongo registry
        run: |
          env
          echo $PATH_TO_SAVE
          echo $DATA_TO_SAVE
